version: 2.1

orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.8.0

jobs:
  build:
    description: Install npm
    # machine option runs your jobs in a dedicated, ephemeral VM that has the following specifications:
    machine: true
    steps:
      - checkout
      # Install node
      - node/install
      # Install npm
      - node/install-npm
      # Download and cache dependencies
      - node/with-cache:
          steps:
            - run:
                name: Install application dependencies
                command: npm install
          # Save cache
          cache-key: package.json
          # Ignore non-checksum cache hits
          use-strict-cache: true
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: web-app
      - gcr/push-image:
          image: web-app

    
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    parameters:
            gcloud-service-key:
                default: GCLOUD_SERVICE_KEY
                description: The gcloud service key
                type: env_var_name
            google-compute-zone:
                default: GOOGLE_COMPUTE_ZONE
                description: The Google compute zone to connect with via the gcloud CLI
                type: env_var_name
            google-project-id:
                default: GOOGLE_PROJECT_ID
                description: The Google project ID to connect with via the gcloud CLI
                type: env_var_name
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: circle-ci-react-cluster
          gcloud-service-key: GCLOUD_SERVICE_KEY
          google-compute-zone: GOOGLE_COMPUTE_ZONE
          google-project-id: GOOGLE_PROJECT_ID
      # Update a deployment's Docker image.
      - gcp-gke/rollout-image:
          cluster: circle-ci-react-cluster
          deployment: circle-ci-react-cluster
          container: dominic-backend
          image: gcr.io/elena-circle-ci-demo/web-app


workflows:
  build_update_deploy:
    jobs:
      - build
      - Build-Push-Image-Docker:
          requires:
            - build
      - deploy:
          requires:
            - Build-Push-Image-Docker
      

